""" Abstract Base class

Revision ID: 8c6d007656f4
Revises: 
Create Date: 2023-06-15 16:42:29.416500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6d007656f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyback_data',
    sa.Column('buyback_id', sa.Integer(), nullable=False),
    sa.Column('key_word', sa.String(), nullable=False),
    sa.Column('product_link', sa.String(), nullable=False),
    sa.Column('item_size', sa.String(), nullable=True),
    sa.Column('bb_amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buyback_data')),
    sa.UniqueConstraint('buyback_id', name=op.f('uq_buyback_data_buyback_id'))
    )
    op.create_table('user_account',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('reg_date', sa.Integer(), nullable=False),
    sa.Column('upd_date', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order'], ['buyback_data.id'], name=op.f('fk_user_account_order_buyback_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_account_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_account')
    op.drop_table('buyback_data')
    # ### end Alembic commands ###
