"""Start Db

Revision ID: e1de071dea54
Revises: fd5a6f695f06
Create Date: 2023-06-04 18:56:41.211042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1de071dea54'
down_revision = 'fd5a6f695f06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('reg_date', sa.Integer(), nullable=False),
    sa.Column('upd_date', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('buyback_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wb_keyword', sa.String(), nullable=False),
    sa.Column('pc_url', sa.String(), nullable=False),
    sa.Column('ordered_amount', sa.Integer(), nullable=False),
    sa.Column('approved_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buyback_data')
    op.drop_table('user_account')
    # ### end Alembic commands ###
